version: '3'
services:
  # db: 
  #   image: mysql:latest
  #   environment:
  #     - MYSQL_DATABASE=php_docker
  #     - MYSQL_USER=php_docker
  #     - MYSQL_PASSWORD=password # this should live in a env var
  #     - MYSQL_ALLOW_EMPTY_PASSWORD=1 # equivalent to True
  #   volumes:
  #     - mysql-data:/var/lib/mysql  # Named volume for data persistence
  www:
    build:
      context: ./php
      dockerfile: Dockerfile
    volumes:
      - "./:/var/www/html" # sync the current dir on local machine to the dir of container
      - shared-data:/var/www/shared
    ports:
      - 8080:80
      - 443:443 # for future ssl traffic
  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin
  #   ports:
  #     - 8001:80
  #   environment:
  #     - PMA_HOST=db
  #     - PMA_PORT=3306

  detectron2:
    build: 
      context: ./dtron
      dockerfile: Dockerfile
    ports:
      # - "65111:22"
      - "5001:5000"  # Expose the port for the API server
    volumes:
      - ./dtron:/app
      - shared-data:/data/shared

    deploy:
          resources:
            reservations:
              devices:
                - driver: nvidia
                  count: 'all'
                  capabilities: [gpu]


  # bgn:
  #   build: 
  #     context: /home/lintzuh@kean.edu/virtualTryOn/HR-VITON/CIHP_PGN
  #     dockerfile: Dockerfile
  #   ports:
  #     - "5003:5000"  # Expose the port for the API server
  #   volumes:
  #     - /home/lintzuh@kean.edu/virtualTryOn/HR-VITON/CIHP_PGN:/app
  #     - shared-data:/data/shared

  #   deploy:
  #         resources:
  #           reservations:
  #             devices:
  #               - driver: nvidia
  #                 count: 'all'
  #                 capabilities: [gpu]

volumes:
  mysql-data:
  shared-data:
    driver: local
    driver_opts:
      type: none
      device: /home/lintzuh@kean.edu/virtualTryOn/projectData
      o: bind
